version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ..:/workspaces/parrhesepstein:cached
    command: sleep infinity
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
